# Generated by Django 3.2 on 2024-02-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_no', models.IntegerField(max_length=4)),
                ('customer', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=200)),
                ('price_amount', models.CharField(max_length=15)),
                ('permit_status', models.CharField(max_length=20)),
                ('date_completed', models.DateField()),
                ('invoice_no', models.IntegerField(max_length=6)),
                ('payment_method', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Submitted', 'Not Submitted')], max_length=20)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_works.customerlist')),
            ],
        ),
    ]
