# Generated by Django 3.2 on 2024-02-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_works', '0002_alter_permits_date_submitted'),
        ('sign_works', '0002_auto_20240205_1154'),
    ]

    operations = [
    ]
