# Generated by Django 3.2 on 2024-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='permit_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
