# Generated by Django 3.2 on 2024-02-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_works', '0003_merge_20240217_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('job_no', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('planning_dept', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Submitted', 'Not Submitted')], max_length=20)),
                ('date_approved', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='permits',
            old_name='city',
            new_name='building_dept',
        ),
        migrations.RemoveField(
            model_name='permits',
            name='date_approved',
        ),
        migrations.AddField(
            model_name='permits',
            name='Bldg_permit_no',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
