# Generated by Django 3.2 on 2024-02-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_works', '0004_auto_20240221_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permits',
            old_name='Bldg_permit_no',
            new_name='bldg_permit_no',
        ),
    ]
