# Generated by Django 3.2 on 2024-02-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_works', '0005_rename_bldg_permit_no_permits_bldg_permit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='permits',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permits',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Submitted', 'Not Submitted'), ('Not Approved', 'Not Pproved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plans',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Submitted', 'Not Submitted'), ('Not Approved', 'Not Pproved')], max_length=20),
        ),
    ]
