# Generated by Django 3.2 on 2024-02-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_works', '0006_auto_20240223_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='permits',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
